/**
 * taxonomy.ts — single source of truth for list dimensions: slugs, display names, and
 * the mappings between TMDb identifiers and our slugs.
 *
 * A movie's tag arrays (industries/countries/languages/genres) hold the SLUGS defined
 * here. Lists are generated by filtering movies on these slugs (see docs/DATA-MODEL.md).
 * Both the fetch scripts (normalizing TMDb data) and the site (building/labelling lists)
 * import from here so the two never drift.
 */

export type Dimension =
  | 'industry'
  | 'country'
  | 'language'
  | 'genre'
  | 'year'
  | 'decade'
  | 'studio'
  | 'theme';

export interface TaxonomyEntry {
  slug: string;
  name: string; // display name
}

/* ------------------------------------------------------------------ countries ------ */
// Keyed by TMDb ISO-3166-1 country code (from production_countries / origin_country).
export const COUNTRIES: Record<string, TaxonomyEntry> = {
  US: { slug: 'united-states', name: 'United States' },
  GB: { slug: 'united-kingdom', name: 'United Kingdom' },
  KR: { slug: 'south-korea', name: 'South Korea' },
  JP: { slug: 'japan', name: 'Japan' },
  IN: { slug: 'india', name: 'India' },
  FR: { slug: 'france', name: 'France' },
  ES: { slug: 'spain', name: 'Spain' },
};

/* ----------------------------------------------------------------- languages ------- */
// Keyed by TMDb ISO-639-1 language code (original_language / spoken_languages).
export const LANGUAGES: Record<string, TaxonomyEntry> = {
  en: { slug: 'english', name: 'English' },
  ko: { slug: 'korean', name: 'Korean' },
  ja: { slug: 'japanese', name: 'Japanese' },
  hi: { slug: 'hindi', name: 'Hindi' },
  fr: { slug: 'french', name: 'French' },
  es: { slug: 'spanish', name: 'Spanish' },
};

/* ------------------------------------------------------------------- genres -------- */
// Keyed by TMDb genre id (from /genre/movie/list). Custom categories (e.g. k-drama) are
// assigned editorially in the fetch step, not derived from a TMDb id — see assignCustom().
export const GENRES: Record<number, TaxonomyEntry> = {
  28: { slug: 'action', name: 'Action' },
  12: { slug: 'adventure', name: 'Adventure' },
  16: { slug: 'animation', name: 'Animation' },
  35: { slug: 'comedy', name: 'Comedy' },
  80: { slug: 'crime', name: 'Crime' },
  99: { slug: 'documentary', name: 'Documentary' },
  18: { slug: 'drama', name: 'Drama' },
  10751: { slug: 'family', name: 'Family' },
  14: { slug: 'fantasy', name: 'Fantasy' },
  36: { slug: 'history', name: 'History' },
  27: { slug: 'horror', name: 'Horror' },
  10402: { slug: 'music', name: 'Music' },
  9648: { slug: 'mystery', name: 'Mystery' },
  10749: { slug: 'romance', name: 'Romance' },
  878: { slug: 'science-fiction', name: 'Science Fiction' },
  53: { slug: 'thriller', name: 'Thriller' },
  10752: { slug: 'war', name: 'War' },
  37: { slug: 'western', name: 'Western' },
};

/* ----------------------------------------------------------------- industries ------ */
// Industry isn't a TMDb field; we derive it from country + language combinations. This
// captures the editorial mapping used in the fetch step.
export const INDUSTRIES: Record<string, TaxonomyEntry> = {
  hollywood: { slug: 'hollywood', name: 'Hollywood' },
  bollywood: { slug: 'bollywood', name: 'Bollywood' },
};

/* ------------------------------------------------- custom (editorial) categories --- */
// Slugs we assign by rule rather than a 1:1 TMDb id. Lets us target long-tail keywords.
export const CUSTOM_GENRES: Record<string, TaxonomyEntry> = {
  'k-drama': { slug: 'k-drama', name: 'K-Drama' },
};

/* ------------------------------------------------------------------- helpers ------- */

/* ---------------------------------------------------- studios (production) --------- */
// Well-known, searchable studios. A film's studio is a PERMANENT property (unlike streaming
// availability), so these lists never go stale. Matched against TMDb production_companies
// by name pattern (TMDb has many company-name variants per studio).
export const STUDIOS: Record<string, TaxonomyEntry> = {
  pixar: { slug: 'pixar', name: 'Pixar' },
  'studio-ghibli': { slug: 'studio-ghibli', name: 'Studio Ghibli' },
  'marvel-studios': { slug: 'marvel-studios', name: 'Marvel Studios' },
  dreamworks: { slug: 'dreamworks', name: 'DreamWorks' },
  a24: { slug: 'a24', name: 'A24' },
  disney: { slug: 'disney', name: 'Walt Disney' },
  'warner-bros': { slug: 'warner-bros', name: 'Warner Bros.' },
  universal: { slug: 'universal', name: 'Universal Pictures' },
  paramount: { slug: 'paramount', name: 'Paramount' },
  columbia: { slug: 'columbia', name: 'Columbia Pictures' },
  lionsgate: { slug: 'lionsgate', name: 'Lionsgate' },
  'new-line': { slug: 'new-line', name: 'New Line Cinema' },
  'focus-features': { slug: 'focus-features', name: 'Focus Features' },
};

// name-pattern → studio slug. Order matters: more specific first.
const STUDIO_PATTERNS: { re: RegExp; slug: string }[] = [
  { re: /\bpixar\b/i, slug: 'pixar' },
  { re: /studio ghibli/i, slug: 'studio-ghibli' },
  { re: /marvel studios/i, slug: 'marvel-studios' },
  { re: /dreamworks/i, slug: 'dreamworks' },
  { re: /\bA24\b/, slug: 'a24' },
  { re: /walt disney (pictures|animation|productions)/i, slug: 'disney' },
  { re: /new line cinema/i, slug: 'new-line' },
  { re: /warner bros/i, slug: 'warner-bros' },
  { re: /universal pictures/i, slug: 'universal' },
  { re: /paramount pictures/i, slug: 'paramount' },
  { re: /columbia pictures/i, slug: 'columbia' },
  { re: /lions ?gate/i, slug: 'lionsgate' },
  { re: /focus features/i, slug: 'focus-features' },
];

/** Map a movie's TMDb production-company names to our studio slugs. */
export function studioSlugsFor(companyNames: string[]): string[] {
  const out = new Set<string>();
  for (const name of companyNames) {
    for (const { re, slug } of STUDIO_PATTERNS) {
      if (re.test(name)) out.add(slug);
    }
  }
  return [...out];
}

/* ---------------------------------------------------- themes (audience/subject) ---- */
// Evergreen audience/subject themes from TMDb keywords. Safe, high-demand search intents
// ("best coming-of-age movies", "movies based on a true story"). NOTE: no "adult" theme —
// AdSense risk. Matched against TMDb keyword names by pattern.
export const THEMES: Record<string, TaxonomyEntry> = {
  'coming-of-age': { slug: 'coming-of-age', name: 'Coming-of-Age' },
  teen: { slug: 'teen', name: 'Teen' },
  'true-story': { slug: 'true-story', name: 'Based on a True Story' },
  'feel-good': { slug: 'feel-good', name: 'Feel-Good' },
  dystopian: { slug: 'dystopian', name: 'Dystopian' },
  heist: { slug: 'heist', name: 'Heist' },
  'time-travel': { slug: 'time-travel', name: 'Time Travel' },
  superhero: { slug: 'superhero', name: 'Superhero' },
};

const THEME_PATTERNS: { re: RegExp; slug: string }[] = [
  { re: /coming.of.age/i, slug: 'coming-of-age' },
  { re: /\b(high school|teenager|teen)\b/i, slug: 'teen' },
  { re: /based on (a )?true (story|event)|biography|biographical/i, slug: 'true-story' },
  { re: /feel.good/i, slug: 'feel-good' },
  { re: /dystopia/i, slug: 'dystopian' },
  { re: /\bheist\b/i, slug: 'heist' },
  { re: /time travel/i, slug: 'time-travel' },
  { re: /superhero/i, slug: 'superhero' },
];

/** Map a movie's TMDb keyword names to our theme slugs. */
export function themeSlugsFor(keywordNames: string[]): string[] {
  const out = new Set<string>();
  for (const name of keywordNames) {
    for (const { re, slug } of THEME_PATTERNS) {
      if (re.test(name)) out.add(slug);
    }
  }
  return [...out];
}

// Country adjectives (for combo titles: "South Korean Crime" not "South Korea Crime").
// Keyed by our country slug; falls back to the country name when absent.
const COUNTRY_ADJECTIVES: Record<string, string> = {
  'south-korea': 'South Korean',
  japan: 'Japanese',
  india: 'Indian',
  france: 'French',
  spain: 'Spanish',
  'united-states': 'American',
  'united-kingdom': 'British',
};

/** Adjective form of a country slug ("south-korea" → "South Korean"). */
export function countryAdjective(slug: string): string {
  return COUNTRY_ADJECTIVES[slug] ?? nameForSlug('country', slug) ?? slug;
}

export function countryEntry(isoCode: string): TaxonomyEntry | undefined {
  return COUNTRIES[isoCode];
}

export function languageEntry(isoCode: string): TaxonomyEntry | undefined {
  return LANGUAGES[isoCode];
}

export function genreEntry(tmdbGenreId: number): TaxonomyEntry | undefined {
  return GENRES[tmdbGenreId];
}

/** Lookup any taxonomy entry's display name from its slug, across all dimensions. */
export function nameForSlug(dimension: Dimension, slug: string): string | undefined {
  const pools: Record<Exclude<Dimension, 'year' | 'decade'>, TaxonomyEntry[]> = {
    industry: Object.values(INDUSTRIES),
    country: Object.values(COUNTRIES),
    language: Object.values(LANGUAGES),
    genre: [...Object.values(GENRES), ...Object.values(CUSTOM_GENRES)],
    studio: Object.values(STUDIOS),
    theme: Object.values(THEMES),
  };
  if (dimension === 'year') return slug;
  if (dimension === 'decade') return slug;
  return pools[dimension].find((e) => e.slug === slug)?.name;
}

/** Derive the decade slug from a release year, e.g. 2019 -> "2010s". */
export function decadeForYear(year: number): string {
  return `${Math.floor(year / 10) * 10}s`;
}
