/**
 * taxonomy.ts — single source of truth for list dimensions: slugs, display names, and
 * the mappings between TMDb identifiers and our slugs.
 *
 * A movie's tag arrays (industries/countries/languages/genres) hold the SLUGS defined
 * here. Lists are generated by filtering movies on these slugs (see docs/DATA-MODEL.md).
 * Both the fetch scripts (normalizing TMDb data) and the site (building/labelling lists)
 * import from here so the two never drift.
 */

export type Dimension = 'industry' | 'country' | 'language' | 'genre' | 'year' | 'decade';

export interface TaxonomyEntry {
  slug: string;
  name: string; // display name
}

/* ------------------------------------------------------------------ countries ------ */
// Keyed by TMDb ISO-3166-1 country code (from production_countries / origin_country).
export const COUNTRIES: Record<string, TaxonomyEntry> = {
  US: { slug: 'united-states', name: 'United States' },
  GB: { slug: 'united-kingdom', name: 'United Kingdom' },
  KR: { slug: 'south-korea', name: 'South Korea' },
  JP: { slug: 'japan', name: 'Japan' },
  IN: { slug: 'india', name: 'India' },
  FR: { slug: 'france', name: 'France' },
  ES: { slug: 'spain', name: 'Spain' },
};

/* ----------------------------------------------------------------- languages ------- */
// Keyed by TMDb ISO-639-1 language code (original_language / spoken_languages).
export const LANGUAGES: Record<string, TaxonomyEntry> = {
  en: { slug: 'english', name: 'English' },
  ko: { slug: 'korean', name: 'Korean' },
  ja: { slug: 'japanese', name: 'Japanese' },
  hi: { slug: 'hindi', name: 'Hindi' },
  fr: { slug: 'french', name: 'French' },
  es: { slug: 'spanish', name: 'Spanish' },
};

/* ------------------------------------------------------------------- genres -------- */
// Keyed by TMDb genre id (from /genre/movie/list). Custom categories (e.g. k-drama) are
// assigned editorially in the fetch step, not derived from a TMDb id — see assignCustom().
export const GENRES: Record<number, TaxonomyEntry> = {
  28: { slug: 'action', name: 'Action' },
  12: { slug: 'adventure', name: 'Adventure' },
  16: { slug: 'animation', name: 'Animation' },
  35: { slug: 'comedy', name: 'Comedy' },
  80: { slug: 'crime', name: 'Crime' },
  99: { slug: 'documentary', name: 'Documentary' },
  18: { slug: 'drama', name: 'Drama' },
  10751: { slug: 'family', name: 'Family' },
  14: { slug: 'fantasy', name: 'Fantasy' },
  36: { slug: 'history', name: 'History' },
  27: { slug: 'horror', name: 'Horror' },
  10402: { slug: 'music', name: 'Music' },
  9648: { slug: 'mystery', name: 'Mystery' },
  10749: { slug: 'romance', name: 'Romance' },
  878: { slug: 'science-fiction', name: 'Science Fiction' },
  53: { slug: 'thriller', name: 'Thriller' },
  10752: { slug: 'war', name: 'War' },
  37: { slug: 'western', name: 'Western' },
};

/* ----------------------------------------------------------------- industries ------ */
// Industry isn't a TMDb field; we derive it from country + language combinations. This
// captures the editorial mapping used in the fetch step.
export const INDUSTRIES: Record<string, TaxonomyEntry> = {
  hollywood: { slug: 'hollywood', name: 'Hollywood' },
  bollywood: { slug: 'bollywood', name: 'Bollywood' },
};

/* ------------------------------------------------- custom (editorial) categories --- */
// Slugs we assign by rule rather than a 1:1 TMDb id. Lets us target long-tail keywords.
export const CUSTOM_GENRES: Record<string, TaxonomyEntry> = {
  'k-drama': { slug: 'k-drama', name: 'K-Drama' },
};

/* ------------------------------------------------------------------- helpers ------- */

export function countryEntry(isoCode: string): TaxonomyEntry | undefined {
  return COUNTRIES[isoCode];
}

export function languageEntry(isoCode: string): TaxonomyEntry | undefined {
  return LANGUAGES[isoCode];
}

export function genreEntry(tmdbGenreId: number): TaxonomyEntry | undefined {
  return GENRES[tmdbGenreId];
}

/** Lookup any taxonomy entry's display name from its slug, across all dimensions. */
export function nameForSlug(dimension: Dimension, slug: string): string | undefined {
  const pools: Record<Exclude<Dimension, 'year' | 'decade'>, TaxonomyEntry[]> = {
    industry: Object.values(INDUSTRIES),
    country: Object.values(COUNTRIES),
    language: Object.values(LANGUAGES),
    genre: [...Object.values(GENRES), ...Object.values(CUSTOM_GENRES)],
  };
  if (dimension === 'year') return slug;
  if (dimension === 'decade') return slug;
  return pools[dimension].find((e) => e.slug === slug)?.name;
}

/** Derive the decade slug from a release year, e.g. 2019 -> "2010s". */
export function decadeForYear(year: number): string {
  return `${Math.floor(year / 10) * 10}s`;
}
